Repository xuri/excelize-cs, pull requests merged in 2025-09, with the labels that each got.

#1 Update GitHub Action configuration and package props
  .github/workflows/build.yml
  Excelize/Excelize.csproj
  Excelize/README.md
  Excelize/chart.png
  Excelize/excelize-cs.png
Labels: size/L

#2 Remove duplicated double quote and social media links
  Excelize/README.md
  README.md
  README_zh.md
Labels: size/XS

#4 Support publish NuGet package on GitHub
  .github/workflows/build.yml
  Excelize/Excelize.csproj
Labels: size/S
